- name: varibles from play level
  hosts: localhost
  vars:
    course: "devops"
    trainer: "siva"
    duration: "110 hrs"
  tasks:
  - name: varibles from tasks level
    vars:
      course: "devops with aws"
    ansible.builtin.debug:
      msg: "Hi we are learning {{course}} trainer is {{trainer}} duration is {{duration}}"