- name: Variables from play
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: getting variables from another source file
    ansible.builtin.debug:
      msg: "we are learning {{course}} trainer is {{trainer}} duration is {{duration}}"