# creating roboshop if user is doesn't exist

- name: creating roboshop if user is doesn't exist
  hosts: web
  become: true
  tasks:
  - name: Getting/fetching roboshop user data
    ansible.builtin.command: id roboshop
    register: user  #user is a varible name here
    ignore_errors: true
  
  - name: displaying roboshop user details
    ansible.builtin.debug:
      msg: "Roboshop user info is {{user}}"

  - name: displaying roboshop user return code (exit status)
    ansible.builtin.debug:
      msg: "Return code of Roboshop user is {{user.rc}}"

  - name: creating roboshop user if already not there
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0
