- name: Installing all the packages
  hosts: web
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: "{{item}}"   # item is default keyword
        state: present
    - name: Displaying installed package
      loop:
      - git
      - postfix
      - nginx
      - mysql

    - name: Displaying installed package
      ansible.builtin.debug:
        msg: "Successfully installed package {{item}}"
      loop:
        - git
        - postfix
        - nginx
        - mysql