- name: Installing all the packages
  hosts: web
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: "{{item}}"   # item is default keyword
        state: present
    - name: Displaying installed package
      loop:
      - git
      - postfix
      - nginx
      - mysql
