- name: Installing all the packages
  hosts: web
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: {{item}}
        status: present
      ansible.builtin.debug:
        msg: "Successfully installed package is {{item}}"
      loop:
      - git
      - postfix
      - nginx
      - mysql