- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
- name: Prinitng success message
  tasks:
    ansible.builtin.debug:
      msg: "Successfully inastlled and running nginx server"